# Generated by Django 6.0.3 on 2026-03-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_issue_ticket_title_remove_ticket_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
    ]
